ms-core/ms-cloud-monitor/src/main/java/com/module/admin/cli/pojo/CliInfo.java
package com.module.admin.cli.pojo;

import java.io.Serializable;
import java.util.Date;

import org.apache.ibatis.type.Alias;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.system.comm.model.BaseEntity;

/**
 * cli_info实体
 * @author yuejing
 * @date 2016-10-20 17:55:37
 * @version V1.0.0
 */
@Alias("cliInfo")
@SuppressWarnings("serial")
@JsonInclude(Include.NON_NULL)
public class CliInfo extends BaseEntity implements Serializable {
	//客户端编号
	private String clientId;
	//名称
	private String name;
	//描叙
	private String remark;
	//ip地址
	private String ip;
	//端口
	private Integer port;
	//密钥
	private String token;
	//添加时间
	private Date createTime;
	//添加人
	private Integer userId;
	//状态[10正常、20停用、30心跳失败]
	private Integer status;
	//活动状态[10正常、20心跳异常]
	private Integer activityStatus;
	//上次活动时间
	private Date activityTime;
	
	//============================== 扩展属性
	//状态名称
	private String statusName;
	//活动状态名称
	private String activityStatusName;
	//搜索字符串
	private String searchString;
	//发布时间
	private Date releaseTime;
	//日志路径
	private String logPath;
	//客户端shell
	private String shellScript;
	//版本编号
	private String version;
	//版本地址
	private String pathUrl;
	
	public String getClientId() {
		return clientId;
	}
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	
	public Integer getPort() {
		return port;
	}
	public void setPort(Integer port) {
		this.port = port;
	}
	
	public String getToken() {
		return token;
	}
	public void setToken(String token) {
		this.token = token;
	}
	
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public Date getActivityTime() {
		return activityTime;
	}
	public void setActivityTime(Date activityTime) {
		this.activityTime = activityTime;
	}
	public String getStatusName() {
		return statusName;
	}
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}
	public String getSearchString() {
		return searchString;
	}
	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}
	public Integer getActivityStatus() {
		return activityStatus;
	}
	public void setActivityStatus(Integer activityStatus) {
		this.activityStatus = activityStatus;
	}
	public String getShellScript() {
		return shellScript;
	}
	public void setShellScript(String shellScript) {
		this.shellScript = shellScript;
	}
	public String getActivityStatusName() {
		return activityStatusName;
	}
	public void setActivityStatusName(String activityStatusName) {
		this.activityStatusName = activityStatusName;
	}
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
	}
	public String getPathUrl() {
		return pathUrl;
	}
	public void setPathUrl(String pathUrl) {
		this.pathUrl = pathUrl;
	}
	public Date getReleaseTime() {
		return releaseTime;
	}
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}
	public String getLogPath() {
		return logPath;
	}
	public void setLogPath(String logPath) {
		this.logPath = logPath;
	}
}

ms-core/ms-cloud-monitor/src/main/java/com/module/admin/code/core/model/Column.java
package com.module.admin.code.core.model;

import com.module.admin.code.constants.DataType;
import com.system.comm.utils.FrameStringUtil;

public class Column {
	//表中的列名
	private String columnName;
	//属性名称
	private String fieldName;
	private int columnType;
	// 最大长度
	private long length;
	// 0:不能为空 1：可以为空
	private int nullAble;
	// 1:是主键
	private int isKey;
	// 1:自动生成或者自动增长
	private int autoGeneral;
	// 列的备注
	private String comments;

	private String typeName;
	private String typeNameFull;

	/*public Column() {
		columnName = "";
		fieldName = "";
		comments = "";
		typeName = "";
		typeNameFull = "";
	}*/

	public String getColumnName() {
		return columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	/**
	 * 首字母大写的属性名称
	 * @return
	 */
	public String getFieldNameFupcase() {
		return FrameStringUtil.setFirstCharUpcase(fieldName);
	}

	public int getColumnType() {
		return columnType;
	}

	public void setColumnType(int columnType) {
		this.columnType = columnType;
		this.setTypeName(DataType.DATA_TYPE[this.columnType]);
		this.setTypeNameFull(DataType.DATA_TYPE_FULL[this.columnType]);
	}

	public long getLength() {
		return length;
	}

	public void setLength(long length) {
		this.length = length;
	}

	public int getNullAble() {
		return nullAble;
	}

	public void setNullAble(int nullAble) {
		this.nullAble = nullAble;
	}

	public int getIsKey() {
		return isKey;
	}

	public void setIsKey(int isKey) {
		this.isKey = isKey;
	}

	public int getAutoGeneral() {
		return autoGeneral;
	}

	public void setAutoGeneral(int autoGeneral) {
		this.autoGeneral = autoGeneral;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getTypeNameFull() {
		return typeNameFull;
	}

	public void setTypeNameFull(String typeNameFull) {
		this.typeNameFull = typeNameFull;
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	/**
	 * @return the comments
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * @param comments
	 *            the comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments == null ? "" : comments;
		this.comments=this.comments.replaceAll("\n", " ");
	}
	
	public String getComments4Page() {
		if(FrameStringUtil.isEmpty(comments)){
			return this.fieldName;
		}
		if(comments.length()>6){
			return comments.substring(0, 6);
		}
		return comments;
	}

}

ms-core/ms-cloud-monitor/src/main/java/com/module/admin/code/core/model/Table.java
package com.module.admin.code.core.model;

import java.util.ArrayList;
import java.util.List;

import com.system.comm.utils.FrameStringUtil;

/**
 * <p>
 * 代码自动生成工具-数据库表信息
 * </p>
 * <p>
 * Description: 主要应用于oracle,sqlserver数据库数据基本操作
 * </p>
 * @author yuejing
 * @version 1.0
 */

public class Table {
	//表名
	private String name;
	//表的注释
	private String tableComment;
	private int columnNum;
	private List<Column> columns;
	//主键
	private Column firstKColumn;
	// 用在java当中的类名称
	private String className;
	// bean的名称，等于className的首字母小写
	private String beanName;
	//主键列
	private List<Column> kcolumns;
	//普通列
	private List<Column> ncolumns;

	public Table() {
	}

	public int getColumnNum() {
		return columnNum;
	}

	/**
	 * 取普通列的数组
	 * @return
	 */
	public List<Column> getNcolumns() {
		return ncolumns;
	}
	public void setNcolumns(List<Column> ncolumns) {
		this.ncolumns = ncolumns;
	}

	/**
	 * 取主键所在列
	 * 
	 * @return
	 */
	public List<Column> getKcolumns() {
		return this.kcolumns;
	}

	public void setKcolumns(List<Column> kcolumns) {
		this.kcolumns = kcolumns;
	}

	public Column getFirstKColumn() {
		return firstKColumn;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name.toLowerCase();
	}

	public void setColumnNum(int columnNum) {
		this.columnNum = columnNum;
	}

	public List<Column> getColumns() {
		return columns;
	}

	public void setColumns(List<Column> columns) {
		this.columns = columns;
		this.columnNum = this.columns.size();
		
		List<Column> kcolumns = new ArrayList<Column>();
		List<Column> ncolumns = new ArrayList<Column>();
		for (Column column : columns) {
			if(column.getIsKey() == 1) {
				kcolumns.add(column);
			} else {
				ncolumns.add(column);
			}
		}
		//设置主键列集合
		setKcolumns(kcolumns);
		//设置普通列集合
		setNcolumns(ncolumns);
		
		//设置第一个主键
		List<Column> r = this.getKcolumns();
		if (r != null && r.size() > 0) {
			setFirstKColumn(r.get(0));
		} else {
			setFirstKColumn(new Column());
		}
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		if (className != null) {
			this.className = FrameStringUtil.setFirstCharUpcase(className);
			setBeanName(FrameStringUtil.setFirstCharLowcase(this.className));
		}
	}

	public String getBeanName() {
		return beanName;
	}

	public void setBeanName(String beanName) {
		if(this.beanName == null) {
			this.beanName = beanName;
		}
	}

	/**
	 * @param firstKColumn
	 *            the firstKColumn to set
	 */
	public void setFirstKColumn(Column firstKColumn) {
		this.firstKColumn = firstKColumn;
	}

	/**
	 * @return the tableComment
	 */
	public String getTableComment() {
		return tableComment;
	}

	/**
	 * @param tableComment the tableComment to set
	 */
	public void setTableComment(String tableComment) {
		this.tableComment = tableComment;
	}

}

ms-core/ms-cloud-monitor/src/main/java/com/module/admin/code/pojo/CodeCreate.java
package com.module.admin.code.pojo;

import java.io.Serializable;
import java.util.Date;

import org.apache.ibatis.type.Alias;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.system.comm.model.BaseEntity;

/**
 * code_create实体
 * @author yuejing
 * @date 2017-07-27 09:06:22
 * @version V1.0.0
 */
@Alias("codeCreate")
@SuppressWarnings("serial")
@JsonInclude(Include.NON_NULL)
public class CodeCreate extends BaseEntity implements Serializable {
	//编号
	private Integer id;
	//源码编号
	private String code;
	//功能包路径
	private String packagePath;
	//状态[10待生成、20生成中、30生成失败、40生成成功]
	private Integer status;
	//下载地址
	private String download;
	//生成完成时间
	private Date finishTime;
	//数据源编号
	private String dsCode;
	//数据库名或sid
	private String dbName;
	//生成的表集合[多个,分隔]
	private String tables;
	//创建时间
	private Date createTime;
	//创建人
	private Integer userId;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	
	public String getPackagePath() {
		return packagePath;
	}
	public void setPackagePath(String packagePath) {
		this.packagePath = packagePath;
	}
	
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public String getDownload() {
		return download;
	}
	public void setDownload(String download) {
		this.download = download;
	}
	
	public Date getFinishTime() {
		return finishTime;
	}
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}
	
	public String getDsCode() {
		return dsCode;
	}
	public void setDsCode(String dsCode) {
		this.dsCode = dsCode;
	}
	
	public String getTables() {
		return tables;
	}
	public void setTables(String tables) {
		this.tables = tables;
	}
	
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public String getDbName() {
		return dbName;
	}
	public void setDbName(String dbName) {
		this.dbName = dbName;
	}
}

ms-core/ms-cloud-monitor/src/main/java/com/module/admin/code/pojo/CodePrj.java
package com.module.admin.code.pojo;

import java.io.Serializable;
import java.util.Date;

import org.apache.ibatis.type.Alias;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.system.comm.model.BaseEntity;

/**
 * code_prj实体
 * @author yuejing
 * @date 2017-07-27 09:06:22
 * @version V1.0.0
 */
@Alias("codePrj")
@SuppressWarnings("serial")
@JsonInclude(Include.NON_NULL)
public class CodePrj extends BaseEntity implements Serializable {
	//编码
	private String code;
	//项目编号
	private Integer prjId;
	//名称
	private String name;
	//创建时间
	private Date createTime;
	//创建人
	private Integer userId;
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	
	public Integer getPrjId() {
		return prjId;
	}
	public void setPrjId(Integer prjId) {
		this.prjId = prjId;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}

ms-core/ms-cloud-monitor/src/main/java/com/module/admin/code/pojo/CodeTemplate.java
package com.module.admin.code.pojo;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.system.comm.model.BaseEntity;

/**
 * code_template实体
 * @author yuejing
 * @date 2017-07-27 09:06:22
 * @version V1.0.0
 */
@Alias("codeTemplate")
@SuppressWarnings("serial")
@JsonInclude(Include.NON_NULL)
public class CodeTemplate extends BaseEntity implements Serializable {
	//源码编号
	private String code;
	//类型[10java、20jsp、30其它文件]CodeTemplateType
	private Integer type;
	//文件名称
	private String name;
	//描叙
	private String remark;
	//后缀
	private String suffix;
	//包名
	private String packageName;
	//模板内容
	private String content;
	//模板路劲
	private String path;
	
	//============================= 扩展属性
	//项目编号
	private Integer prjId;
	//创建人
	private Integer userId;
	//类型名称
	private String typeName;
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	
	public Integer getType() {
		return type;
	}
	public void setType(Integer type) {
		this.type = type;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public String getPackageName() {
		return packageName;
	}
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}
	
	public String getSuffix() {
		return suffix;
	}
	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	public Integer getPrjId() {
		return prjId;
	}
	public void setPrjId(Integer prjId) {
		this.prjId = prjId;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public String getTypeName() {
		return typeName;
	}
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
}

ms-core/ms-cloud-monitor/src/main/java/com/module/admin/ms/pojo/MsConfig.java
package com.module.admin.ms.pojo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.type.Alias;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.system.comm.model.BaseEntity;

/**
 * ms_config实体
 * @author yuejing
 * @date 2017-04-21 16:02:31
 * @version V1.0.0
 */
@Alias("msConfig")
@SuppressWarnings("serial")
@JsonInclude(Include.NON_NULL)
public class MsConfig extends BaseEntity implements Serializable {
	//编号
	private Integer configId;
	//文件名称
	private String name;
	//备注
	private String remark;
	//是否使用
	private Integer isUse;
	//创建日期
	private Date createTime;
	//添加人
	private Integer userId;
	//项目编号
	private Integer prjId;
	
	//========================== 扩展属性
	//是否使用显示值
	private String isUseName;
	//属性集合
	private List<MsConfigValue> values;
	//项目名称
	private String prjName;
	
	public Integer getConfigId() {
		return configId;
	}
	public void setConfigId(Integer configId) {
		this.configId = configId;
	}
	
	public String getIsUseName() {
		return isUseName;
	}
	public void setIsUseName(String isUseName) {
		this.isUseName = isUseName;
	}
	public List<MsConfigValue> getValues() {
		return values;
	}
	public void setValues(List<MsConfigValue> values) {
		this.values = values;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getPrjName() {
		return prjName;
	}
	public void setPrjName(String prjName) {
		this.prjName = prjName;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public Integer getPrjId() {
		return prjId;
	}
	public void setPrjId(Integer prjId) {
		this.prjId = prjId;
	}
	public Integer getIsUse() {
		return isUse;
	}
	public void setIsUse(Integer isUse) {
		this.isUse = isUse;
	}
	
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}

ms-core/ms-cloud-monitor/src/main/resources/template/code/prod/controller.ftl
package ${packagePath}.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;

import com.moudle.admin.common.controller.BaseController;
import ${packagePath}.pojo.${table.className};
import ${packagePath}.service.${table.className}Service;
import com.system.handle.model.ResponseCode;
import com.system.handle.model.ResponseFrame;

/**
 * ${tablename} Controller
 * @author ${user}
 * @date ${dateTime}
 * @version ${version}
 */
@Controller
public class ${table.className}Controller extends BaseController {

	private static final Logger LOGGER = LoggerFactory.getLogger(${table.className}Controller.class);

	@Autowired
	private ${table.className}Service ${table.beanName}Service;
	
	@RequestMapping(value = "/${table.beanName}/f-view/manager")
    public String manager(HttpServletRequest request, HttpServletResponse response,
    		ModelMap modelMap) {
		return "admin/${moduleName}/${table.beanName}-manager";
    }

    @RequestMapping(value = "/${table.beanName}/f-view/edit")
    public String edit(HttpServletRequest request, HttpServletResponse response,
    		ModelMap modelMap, ${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
    	if(id != null) {
    		${table.className} ${table.beanName} = ${table.beanName}Service.get(${table.firstKColumn.fieldName});
    		modelMap.put("${table.beanName}", ${table.beanName});
    	}
		return "admin/${moduleName}/${table.beanName}-edit";
    }
    
    @RequestMapping(value = "/${table.beanName}/f-json/get")
    @ResponseBody
    public void get(HttpServletRequest request, HttpServletResponse response,
    		${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
        ResponseFrame frame = null;
		try {
			frame = new ResponseFrame();
			${table.className} ${table.beanName} = ${table.beanName}Service.get(id);
			frame.setBody(${table.beanName});
			frame.setSucc();
		} catch (Exception e) {
			LOGGER.error("异常: " + e.getMessage(), e);
			frame = new ResponseFrame(ResponseCode.FAIL);
		}
		writerJson(response, frame);
    }
    
    @RequestMapping(value = "/${table.beanName}/f-json/pageQuery")
    @ResponseBody
    public void pageQuery(HttpServletRequest request, HttpServletResponse response,
    		${table.className} ${table.beanName}) {
        ResponseFrame frame = null;
		try {
			frame = ${table.beanName}Service.pageQuery(${table.beanName});
			frame.setBody(frame);
			frame.setSucc();
		} catch (Exception e) {
			LOGGER.error("异常: " + e.getMessage(), e);
			frame = new ResponseFrame(ResponseCode.FAIL);
		}
		writerJson(response, frame);
    }

    @RequestMapping(value = "/${table.beanName}/f-json/save")
    @ResponseBody
    public void save(HttpServletRequest request, HttpServletResponse response,
    		${table.className} ${table.beanName}) {
        ResponseFrame frame = null;
		try {
			frame = ${table.beanName}Service.saveOrUpdate(${table.beanName});
			frame.setBody(frame);
			frame.setSucc();
		} catch (Exception e) {
			LOGGER.error("异常: " + e.getMessage(), e);
			frame = new ResponseFrame(ResponseCode.FAIL);
		}
		writerJson(response, frame);
    }

    @RequestMapping(value = "/${table.beanName}/f-json/delete")
    @ResponseBody
    public void delete(HttpServletRequest request, HttpServletResponse response,
    		${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
        ResponseFrame frame = new ResponseFrame();
		try {
			${table.beanName}Service.delete(${table.firstKColumn.fieldName});
			frame.setSucc();
		} catch (Exception e) {
			LOGGER.error("异常: " + e.getMessage(), e);
			frame.setCode(ResponseCode.FAIL.getCode());
		}
		writerJson(response, frame);
    }
}

ms-core/ms-cloud-monitor/src/main/resources/template/code/prod/dao.ftl
package ${packagePath}.dao;

import org.springframework.stereotype.Component;

import ${packagePath}.pojo.${table.className};
import com.system.comm.model.Page;
import com.system.dao.BaseDao;
import com.system.dao.sql.QuerySql;

/**
 * ${tablename} Dao
 * @author ${user}
 * @date ${dateTime}
 * @version ${version}
 */
@Component
public class ${table.className}Dao extends BaseDao {

	public void save(${table.className} ${table.beanName}) {
		super.save(${table.beanName});
	}
	
	public void update(${table.className} ${table.beanName}) {
		super.update(${table.beanName});
	}

	public ${table.className} get(${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
		return super.get(${table.className}.class, ${table.firstKColumn.fieldName});
	}

	public Page<${table.className}> pageQuery(${table.className} ${table.beanName}) {
		QuerySql sql = new QuerySql(${table.className}.class);
		//sql.addCondLike("name", ${table.beanName}.getName());
		Page<${table.className}> page = super.pageQuery(sql.getSql(), ${table.beanName}.getPage(), ${table.beanName}.getSize(), ${table.className}.class, sql.getParams());
		return page;
	}
	
	public void delete(${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
		super.delete(${table.className}.class, ${table.firstKColumn.fieldName});
	}
}

ms-core/ms-cloud-monitor/src/main/resources/template/code/prod/service.ftl
package ${packagePath}.service;

import org.springframework.stereotype.Component;

import ${packagePath}.pojo.${table.className};
import com.system.handle.model.ResponseFrame;

/**
 * ${tablename} Service
 * @author ${user}
 * @date ${dateTime}
 * @version ${version}
 */
@Component
public interface ${table.className}Service {
	
	/**
	 * saveOrUpdate
	 * @param ${table.beanName}
	 * @return
	 */
	public ResponseFrame saveOrUpdate(${table.className} ${table.beanName});
	
	/**
	 * ${table.firstKColumn.fieldName} get ${table.className}
	 * @param ${table.firstKColumn.fieldName}
	 * @return
	 */
	public ${table.className} get(${table.firstKColumn.typeName} ${table.firstKColumn.fieldName});

	/**
	 * pageQuery ${table.className}
	 * @param ${table.beanName}
	 * @return
	 */
	public ResponseFrame pageQuery(${table.className} ${table.beanName});
	
	/**
	 * ${table.firstKColumn.fieldName} delete ${table.className}
	 * @param ${table.firstKColumn.fieldName}
	 * @return
	 */
	public ResponseFrame delete(${table.firstKColumn.typeName} ${table.firstKColumn.fieldName});
}

ms-core/ms-cloud-monitor/src/main/resources/template/code/prod/serviceImpl.ftl
package ${packagePath}.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import ${packagePath}.dao.${table.className}Dao;
import ${packagePath}.pojo.${table.className};
import ${packagePath}.service.${table.className}Service;
import com.system.comm.model.Page;
import com.system.handle.model.ResponseFrame;
import com.system.handle.model.ResponseCode;

/**
 * ${tablename} Service
 * @author ${user}
 * @date ${dateTime}
 * @version ${version}
 */
@Component
public class ${table.className}ServiceImpl implements ${table.className}Service {

	@Autowired
	private ${table.className}Dao ${table.beanName}Dao;
	
	@Override
	public ResponseFrame saveOrUpdate(${table.className} ${table.beanName}) {
		ResponseFrame frame = new ResponseFrame();
		if(${table.beanName}.get${table.firstKColumn.fieldNameFupcase}() == null) {
			${table.beanName}Dao.save(${table.beanName});
		} else {
			${table.beanName}Dao.update(${table.beanName});
		}
		frame.setCode(ResponseCode.SUCC.getCode());
		return frame;
	}

	@Override
	public ${table.className} get(${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
		return ${table.beanName}Dao.get(${table.firstKColumn.fieldName});
	}

	@Override
	public ResponseFrame pageQuery(${table.className} ${table.beanName}) {
		${table.beanName}.setDefPageSize();
		ResponseFrame frame = new ResponseFrame();
		Page<${table.className}> page = ${table.beanName}Dao.pageQuery(${table.beanName});
		frame.setBody(page);
		frame.setSucc();
		return frame;
	}
	
	@Override
	public ResponseFrame delete(${table.firstKColumn.typeName} ${table.firstKColumn.fieldName}) {
		ResponseFrame frame = new ResponseFrame();
		${table.beanName}Dao.delete(${table.firstKColumn.fieldName});
		frame.setCode(ResponseCode.SUCC.getCode());
		return frame;
	}
}